# CMake generated Testfile for 
# Source directory: E:/project/astrology/JPL-Moshier-Ephemeris
# Build directory: E:/project/astrology/JPL-Moshier-Ephemeris/build-local
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[julian]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Debug/test_julian.exe")
  set_tests_properties([=[julian]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;95;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[julian]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Release/test_julian.exe")
  set_tests_properties([=[julian]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;95;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[julian]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/MinSizeRel/test_julian.exe")
  set_tests_properties([=[julian]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;95;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[julian]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/RelWithDebInfo/test_julian.exe")
  set_tests_properties([=[julian]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;95;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[julian]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[api_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Debug/test_api_contract.exe")
  set_tests_properties([=[api_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;99;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[api_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Release/test_api_contract.exe")
  set_tests_properties([=[api_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;99;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[api_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/MinSizeRel/test_api_contract.exe")
  set_tests_properties([=[api_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;99;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[api_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/RelWithDebInfo/test_api_contract.exe")
  set_tests_properties([=[api_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;99;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[api_contract]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[jpl_runtime]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Debug/test_jpl_runtime.exe")
  set_tests_properties([=[jpl_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;103;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[jpl_runtime]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Release/test_jpl_runtime.exe")
  set_tests_properties([=[jpl_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;103;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[jpl_runtime]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/MinSizeRel/test_jpl_runtime.exe")
  set_tests_properties([=[jpl_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;103;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[jpl_runtime]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/RelWithDebInfo/test_jpl_runtime.exe")
  set_tests_properties([=[jpl_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;103;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[jpl_runtime]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[all_constants]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Debug/test_all_constants.exe")
  set_tests_properties([=[all_constants]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;107;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[all_constants]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Release/test_all_constants.exe")
  set_tests_properties([=[all_constants]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;107;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[all_constants]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/MinSizeRel/test_all_constants.exe")
  set_tests_properties([=[all_constants]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;107;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[all_constants]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/RelWithDebInfo/test_all_constants.exe")
  set_tests_properties([=[all_constants]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;107;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[all_constants]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[all_functions]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Debug/test_all_functions.exe")
  set_tests_properties([=[all_functions]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;111;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[all_functions]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Release/test_all_functions.exe")
  set_tests_properties([=[all_functions]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;111;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[all_functions]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/MinSizeRel/test_all_functions.exe")
  set_tests_properties([=[all_functions]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;111;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[all_functions]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/RelWithDebInfo/test_all_functions.exe")
  set_tests_properties([=[all_functions]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;111;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[all_functions]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[analytical_validation]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Debug/test_analytical_validation.exe")
  set_tests_properties([=[analytical_validation]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;115;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[analytical_validation]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Release/test_analytical_validation.exe")
  set_tests_properties([=[analytical_validation]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;115;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[analytical_validation]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/MinSizeRel/test_analytical_validation.exe")
  set_tests_properties([=[analytical_validation]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;115;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[analytical_validation]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/RelWithDebInfo/test_analytical_validation.exe")
  set_tests_properties([=[analytical_validation]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;115;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[analytical_validation]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[extra_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Debug/test_extra_contract.exe")
  set_tests_properties([=[extra_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;119;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[extra_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Release/test_extra_contract.exe")
  set_tests_properties([=[extra_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;119;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[extra_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/MinSizeRel/test_extra_contract.exe")
  set_tests_properties([=[extra_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;119;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[extra_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/RelWithDebInfo/test_extra_contract.exe")
  set_tests_properties([=[extra_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;119;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[extra_contract]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[mapped_adversarial]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Debug/test_mapped_adversarial.exe")
  set_tests_properties([=[mapped_adversarial]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;126;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[mapped_adversarial]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Release/test_mapped_adversarial.exe")
  set_tests_properties([=[mapped_adversarial]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;126;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[mapped_adversarial]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/MinSizeRel/test_mapped_adversarial.exe")
  set_tests_properties([=[mapped_adversarial]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;126;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[mapped_adversarial]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/RelWithDebInfo/test_mapped_adversarial.exe")
  set_tests_properties([=[mapped_adversarial]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;126;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[mapped_adversarial]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[extra_adversarial]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Debug/test_extra_adversarial.exe")
  set_tests_properties([=[extra_adversarial]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;133;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[extra_adversarial]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/Release/test_extra_adversarial.exe")
  set_tests_properties([=[extra_adversarial]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;133;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[extra_adversarial]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/MinSizeRel/test_extra_adversarial.exe")
  set_tests_properties([=[extra_adversarial]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;133;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[extra_adversarial]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-local/RelWithDebInfo/test_extra_adversarial.exe")
  set_tests_properties([=[extra_adversarial]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;133;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[extra_adversarial]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[engine_matrix]=] "/bin/bash" "E:/project/astrology/JPL-Moshier-Ephemeris/tools/run_engine_matrix.sh")
  set_tests_properties([=[engine_matrix]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;138;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[engine_matrix]=] "/bin/bash" "E:/project/astrology/JPL-Moshier-Ephemeris/tools/run_engine_matrix.sh")
  set_tests_properties([=[engine_matrix]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;138;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[engine_matrix]=] "/bin/bash" "E:/project/astrology/JPL-Moshier-Ephemeris/tools/run_engine_matrix.sh")
  set_tests_properties([=[engine_matrix]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;138;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[engine_matrix]=] "/bin/bash" "E:/project/astrology/JPL-Moshier-Ephemeris/tools/run_engine_matrix.sh")
  set_tests_properties([=[engine_matrix]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;138;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[engine_matrix]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[api_inventory]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_inventory.ps1")
  set_tests_properties([=[api_inventory]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;145;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[api_inventory]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_inventory.ps1")
  set_tests_properties([=[api_inventory]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;145;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[api_inventory]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_inventory.ps1")
  set_tests_properties([=[api_inventory]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;145;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[api_inventory]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_inventory.ps1")
  set_tests_properties([=[api_inventory]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;145;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[api_inventory]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[symbol_coverage]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_symbol_coverage.ps1")
  set_tests_properties([=[symbol_coverage]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;150;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[symbol_coverage]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_symbol_coverage.ps1")
  set_tests_properties([=[symbol_coverage]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;150;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[symbol_coverage]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_symbol_coverage.ps1")
  set_tests_properties([=[symbol_coverage]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;150;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[symbol_coverage]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_symbol_coverage.ps1")
  set_tests_properties([=[symbol_coverage]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;150;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[symbol_coverage]=] NOT_AVAILABLE)
endif()
