# CMake generated Testfile for 
# Source directory: E:/project/astrology/JPL-Moshier-Ephemeris
# Build directory: E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[julian]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/Debug/test_julian.exe")
  set_tests_properties([=[julian]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;61;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[julian]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/Release/test_julian.exe")
  set_tests_properties([=[julian]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;61;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[julian]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/MinSizeRel/test_julian.exe")
  set_tests_properties([=[julian]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;61;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[julian]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/RelWithDebInfo/test_julian.exe")
  set_tests_properties([=[julian]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;61;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[julian]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[api_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/Debug/test_api_contract.exe")
  set_tests_properties([=[api_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;65;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[api_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/Release/test_api_contract.exe")
  set_tests_properties([=[api_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;65;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[api_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/MinSizeRel/test_api_contract.exe")
  set_tests_properties([=[api_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;65;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[api_contract]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/RelWithDebInfo/test_api_contract.exe")
  set_tests_properties([=[api_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;65;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[api_contract]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[jpl_runtime]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/Debug/test_jpl_runtime.exe")
  set_tests_properties([=[jpl_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;69;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[jpl_runtime]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/Release/test_jpl_runtime.exe")
  set_tests_properties([=[jpl_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;69;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[jpl_runtime]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/MinSizeRel/test_jpl_runtime.exe")
  set_tests_properties([=[jpl_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;69;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[jpl_runtime]=] "E:/project/astrology/JPL-Moshier-Ephemeris/build-vcpkg/RelWithDebInfo/test_jpl_runtime.exe")
  set_tests_properties([=[jpl_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;69;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[jpl_runtime]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[api_inventory]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_inventory.ps1")
  set_tests_properties([=[api_inventory]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;73;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[api_inventory]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_inventory.ps1")
  set_tests_properties([=[api_inventory]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;73;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[api_inventory]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_inventory.ps1")
  set_tests_properties([=[api_inventory]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;73;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[api_inventory]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_inventory.ps1")
  set_tests_properties([=[api_inventory]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;73;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[api_inventory]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[symbol_coverage]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_symbol_coverage.ps1")
  set_tests_properties([=[symbol_coverage]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;78;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[symbol_coverage]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_symbol_coverage.ps1")
  set_tests_properties([=[symbol_coverage]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;78;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[symbol_coverage]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_symbol_coverage.ps1")
  set_tests_properties([=[symbol_coverage]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;78;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[symbol_coverage]=] "C:/Program Files/PowerShell/7/pwsh.exe" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "E:/project/astrology/JPL-Moshier-Ephemeris/tests/test_symbol_coverage.ps1")
  set_tests_properties([=[symbol_coverage]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;78;add_test;E:/project/astrology/JPL-Moshier-Ephemeris/CMakeLists.txt;0;")
else()
  add_test([=[symbol_coverage]=] NOT_AVAILABLE)
endif()
